############################################
#### Server
server:
  port: 8080

############################################
####  Spring
spring:
  datasource:
    writer:
      jdbc-url: jdbc:postgresql://aurora-dev-p18.cluster-c2as9ee4bg3m.ap-northeast-2.rds.amazonaws.com:5432/notify_mylgdb
      username: ENC(O200GY14sW9KJ6kZAqzpxH48z2oqQWRNmi5jDzKa/rGkQrgMNAHnSN14yUR5c+Af)
      password: ENC(bInqnTHoQZ1thEwxF0t0LCavzB25y3dbkehsd87sVoLfvEcesKN3n+mSd0dr/hRQ)
      minimum-idle: 5
      maximum-pool-size: 5
    reader:
      jdbc-url: jdbc:postgresql://aurora-dev-p18.cluster-ro-c2as9ee4bg3m.ap-northeast-2.rds.amazonaws.com:5432/notify_mylgdb
      username: ENC(bsVTU6HilFT0iZBi4jdIAAnqkpttV3UaG4NI2yvS6xKGkNuUzNV2Dsh54BvAhj64)
      password: ENC(yJywFK8Os/0byQiFx+YBkpipAeGdLWcPClqKwLvqKR1eljcqUufovSYRf36FL4H6)
      minimum-idle: 5
      maximum-pool-size: 5

  ## Cache - Redis
  redis.cluster.nodes: redis-dev-iptv-dev-msa-01.b4rwjf.clustercfg.apn2.cache.amazonaws.com:6379

############################################
#### Logging
logging:
  level:
    com.lguplus.fleta: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql:
          BasicBinder: TRACE
          BasicExtractor: OFF
  pattern.level: "%5p [${spring.application.name}][%X{saId:-}][%X{stbMac:-}]"


  #### Message Stream - Kafka
  kafka:
    bootstrap-servers:
      - b-1.msk-dev-iptv-dev.b1moez.c2.kafka.ap-northeast-2.amazonaws.com
      - b-2.msk-dev-iptv-dev.b1moez.c2.kafka.ap-northeast-2.amazonaws.com
      - b-3.msk-dev-iptv-dev.b1moez.c2.kafka.ap-northeast-2.amazonaws.com
      - b-4.msk-dev-iptv-dev.b1moez.c2.kafka.ap-northeast-2.amazonaws.com
      - b-5.msk-dev-iptv-dev.b1moez.c2.kafka.ap-northeast-2.amazonaws.com
      - b-6.msk-dev-iptv-dev.b1moez.c2.kafka.ap-northeast-2.amazonaws.com

############################################
#### Other Domain Application Service
service:
  programming:
    url: http://programming.fleta.com
  searchword:
    url: http://searchword.fleta.com
  settings:
    url: http://settings.fleta.com
  vodlookup:
    url: http://vodlookup.fleta.com
  channel:
    url: http://channel.fleta.com
  personalization:
    url: http://personalization.fleta.com
  subscriber:
    url: http://subscriber.fleta.com



############################################
#### Feign Client 설정
feign:
  client:
    config:
      default: # 전역 이름
        connectTimeout: 1000
        readTimeout: 1000
      pushannounce: # Push Announce
        connectTimeout: 2000
        #readTimeout: 2000
        loggerLevel: full # NONE, BASIC, HEADERS, FULL
        #defaultRequestHeaders:
        #  header1: header1Value
        requestInterceptors:
          - com.lguplus.fleta.config.PushFeignInterceptor
        errorDecoder: com.lguplus.fleta.provider.rest.PushAnnounceClientImpl.PushErrorDecoder
