spring.profiles.active: local



### 로컬 환경
---
spring:
  config:
    activate.on-profile: local
    import: optional:configserver:${CONFIG_SERVER:https://dev-arishem.releng.ciptv.uplus.co.kr/}



### 로컬 외 환경
---
spring:
  config:
    activate.on-profile: tst,dev,stp,stg,shd,prd
    import: optional:configserver:${CONFIG_SERVER:http://arishem.up.internal:80/}



### 로컬 & 로컬 외 환경 공통
---
spring:
  application.name: notify
  cloud.config:
    fail-fast: true
    name: ${spring.application.name},push,mmsagent,smsagent
    profile: ${spring.profiles.active}
    searchPaths:
      - '{application}'
      - '{application}/*'
  messages:
    basename: messages/response
    encoding: utf-8
