name: STG Build

on:
  create

jobs:
  release:
    if: ${{ startsWith(github.ref_name, 'release/') }}
    runs-on: [ 'self-hosted', 'shared-eks', 'repo' ]
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build and ECR Upload
        id: build
        uses: ./.github/actions/common-build

      - name: helm chart stg version tagging
        if: ${{ startsWith(github.ref_name, 'release/') }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONS_SECRET }}
          repository: LGUPLUS-IPTV-MSA/helm-charts
          event-type: app_image_update
          client-payload: '{"app_name": "${{ steps.build.outputs.appName }}", "app_version": "${{ steps.build.outputs.imageTag }}", "deploy_env": "stg"}'

      - name: slack message
        if: always()
        uses: nooose/custom-slack-message@master
        with:
          type: build
          token: ${{ secrets.ACTIONS_SECRET }}
          slack_webhook: ${{ secrets.SLACK_STG_WEBHOOK }}
          slack_color: ${{ job.status }}