name: codeQuality

on:
  push:
    branches: [ feature/sonar_badge ]
jobs:
  JaCoCo:
    if: ${{ github.base_ref == 'develop' }}
    runs-on: [ 'self-hosted', 'shared-eks', 'repo' ]
    steps:
      - name: Get app name from repo
        run: echo "APP_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed 's/-service$//g')" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run test
        run: SPRING_PROFILES_ACTIVE=tst ./gradlew test -PexcludeTests='**/SwaggerTest'

      - name: Gather Reports
        run: ./gradlew allCoverage

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.5.0
        with:
          jacoco-csv-file: build/reports/jacoco/allCoverage/allCoverage.csv
          badges-directory: ./report
          colors : '#4c1 #4c1 #4c1 #4c1 #fe7d37 #e05d44'
          intervals: 60 60 60 60 50 0

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Report to Sonarqube
        run: ./gradlew sonarqube -Psonarqube_token="${{ secrets.SONARQUBE_TOKEN }}" --no-daemon

      - name: wget
        run: |
          wget -O ./report/sonar_pass.svg "https://sonarqube.releng.ciptv.uplus.co.kr/api/project_badges/measure?project=com.lguplus.${{ env.APP_NAME }}&metric=alert_status&token=${{secrets.SONARQUBE_TOKEN_APP}}"

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: report
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Add Badge and report by Action"
