name: docsCI

on:
  push:
    branches: [ feature/docs ]

jobs:
  test:
    runs-on: [ 'self-hosted', 'shared-eks', 'repo' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test boot module and Generate Docs with Gradle
        run: ./gradlew :boot:test

      - name: Copy document files
        run: |
          mkdir -p docs
          cp subprojects/boot/build/swagger/swagger.json docs/swagger.json
          cp subprojects/boot/build/docs/asciidoc/swagger.html docs/index.html

      - name: Pushes docs to docs repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'docs'
          target-directory: 'notifyication'
          destination-github-username: 'LGUPLUS-IPTV-MSA'
          destination-repository-name: 'rabbi'
          user-email: gooah@lguplus.co.kr
          target-branch: main