name: rabbi

on:
  push:
    branches: [ develop, feature/deviceinfoDocs ]
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'README.md'

jobs:
  test:
    runs-on: [ 'self-hosted', 'shared-eks', 'repo' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test and Generate Docs with Gradle
        run: ./gradlew asciidoctor

      - name: Copy document files
        run: |
          mkdir -p docs
          cp subprojects/presentation/build/docs/asciidoc/index.html docs/index.html

      - name: Pushes docs to docs repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'docs'
          target-directory: 'notify'
          destination-github-username: 'LGUPLUS-IPTV-MSA'
          destination-repository-name: 'rabbi'
          user-email: etti10@lguplus.co.kr
          target-branch: main

      #jacoco-badge
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.5.0
        with:
          jacoco-csv-file: subprojects/presentation/build/JacocoReportDir/test/jacocoTestReport.csv
          badges-directory: ./report
          colors : '#4c1 #4c1 #4c1 #4c1 #fe7d37 #e05d44'
          intervals: 60 60 60 60 50 0

#      - name: Copy jacoco files
#        run: |
#          cp -r subprojects/presentation/build/JacocoReportDir/test/html

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: subprojects/presentation/build/JacocoReportDir/test/html

      - name: Download Output Directory
        uses: actions/download-artifact@v2
        with:
          name: jacoco-report
          path: report/

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: jacoco-badge
          FOLDER: report
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Add Badge and report by Action"
      #end-jacoco-badge
